import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const commissioner = Commissioner({
	variable: "--font-commissioner",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${commissioner.variable} antialiased flex flex-col border min-h-screen`}
			>
				<Navbar />
				<div className='flex-1'>{children}</div>
				<footer className='row-start-3 flex gap-6 flex-wrap items-center justify-center w-screen h-[140px] absolute bottom-0'>
					<div
						className='absolute left-0 w-screen h-[140px]'
						style={{
							background:
								"linear-gradient(to left, #EBA392, #E67E6F, #781542,#481A63, #00758A)",
						}}
					/>
					<div
						className='absolute left-0 w-screen h-[140px]'
						style={{
							background:
								"linear-gradient(to bottom, #000000, rgba(0,0,0,0))",
						}}
					/>
				</footer>
			</body>
		</html>
	);
}
